before_script:
  - export GOPATH=$(pwd)

stages:
  - build
  
vet:
  image: golang:1.5
  stage: build
  script:
    - go tool vet -composites=false ./*.go
    - go tool vet -composites=false -shadow=true examples/*.go

compile-go-1.4:
  image: golang:1.4
  stage: build
  script:
    - git submodule update --init
    - (go build recaptcha.go;  if [ $? -ne 0 ]; then exit 66; fi);
    - (for f in examples/*.go; do echo "-> go build $f"; go build $f; if [ $? -ne 0 ]; then exit 66; fi; done);

compile-go-1.5:
  image: golang:1.5
  stage: build
  script:
    - git submodule update --init
    - (go build recaptcha.go;  if [ $? -ne 0 ]; then exit 66; fi);
    - (for f in examples/*.go; do echo "-> go build $f";  go build $f; if [ $? -ne 0 ]; then exit 66; fi; done);